library(lubridate)
data<-read.delim("data.txt", sep = ";") 
data$Date <- strptime(data$Date, "%d/%m/%Y") 
data<-subset(data, Date=="2007-02-01" | Date=="2007-02-02") 
data$Global_active_power<- as.numeric(data$Global_active_power)
data$time2 <- paste(data$Date, data$Time)
data$time2 <- ymd_hms(data$time2)
png("plot2.png", width = 480, height = 480)
plot(data$time2,data$Global_active_power,
     ylab = "Global active power (kilowatts)", type="l", xlab="")
dev.off()
